### ISSUE TITLE
Retire Emy 😢

### ISSUE THREAD

**Issue by querkmachine** [querkmachine/beeps.website#39]
Emy (the robot bat) is my, now, old fursona. As much as she's been the face of my website for some years now, her direct association with me is a lot weaker than it once was. Oh hey, [I wrote a whole blog post about this](https://beeps.website/blog/2023-08-27-the-next-generation/).

Emy has been gradually replaced by Ash across various online premises, and she should probably disappear from the site at some point too. This would require the creation or commissioning of some new artwork.

Old blog posts with Emy character callouts will remain as they are, as will the associated credit in the colophon.

The website's favicon, which is based on Emy's head, will probably not change either. (Funnily enough, the basic concept of it pre-dates Emy anyway.)

## Todo

- [x] Scope document written up
- [x] Commission contract agreed
- [x] Artwork delivered
  - [x] Homepage introduction
  - [x] Homepage blog post list
  - [x] Site-wide footer
  - [x] 404 page
  - [x] OpenGraph image
- [x] Artwork implemented
  - [x] Homepage introduction
  - [x] Homepage blog post list
  - [x] Site-wide footer
  - [x] 404 page
  - [x] OpenGraph image

**Comment by querkmachine** [comment]
Probably need to commission s'more art before this becomes possible to finish.

**Comment by querkmachine** [comment]
Currently using emoji from Caius for the homepage sections. Should probably commission more of those. 

Considering trying something a little different for the footer and have either a single larger piece that interacts with the bar in a way ([like this one by Tux](https://cohost.org/shapeshifter-shenanigans/post/3991441-you-ve-wandered-i)) or a kind 'knolled' collage of things ([like this one also by Tux](https://shapeshifter-shenanigans.tumblr.com/post/701648574253039616/some-stuff-i-found-around-my-room-and-some-things)). 

Not really had any ideas for the 404 page or OpenGraph image. I suppose they could reuse the first footer idea, it'd fit quite well with how the latter is currently designed.

**Comment by querkmachine** [comment]
Colour scheme changes separated out into #46 so that procuring artwork assets isn't blocking those changes.

**Comment by querkmachine** [comment]
Assets commissioned. Might be a couple of months until they're complete, however.
